"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['Cecilia5.py']
APP_NAME = 'Cecilia5'
DATA_FILES = ['Resources/']
OPTIONS = {'argv_emulation': False,
           'iconfile': 'Resources/Cecilia5.icns'}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
